apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-project
  template:
    metadata:
      labels:
        app: webapp-project
    spec:
      containers:
        - name: webapp
          image: sbgore/project:project
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webapp-project
